== Gestion d'erreurs

[quote]
Build to fail, and fail nicely

Dans la partie <<Validation systématique des données>> nous avons pu voir que la vérification des données entraîne soit une acceptation soit un rejet de celles-ci.

Dans la présente partie, nous aborderons *les traitements relatifs au rejet des données*.

=== Différentes politiques

Nous avons aussi vu qu'un projet, une application, un programme sont découpés en composants, et ces composants peuvent être de deux types :

* des composants purement internes
* des composants ouverts à l'extérieur
** dont ceux interagissant avec des composants externes "machine"
** dont ceux intéragissant avec des éléments externes "humains"

Ce découpage permettra de définir différentes consignes de rejet, décrites ci-dessous

=== Rejet internes

On appellera *composant interne* tout composant dont l'appel *utilise la même technique que l'appelant*. Par exemple une fonction qui appelle une autre fonction, etc...

==== Bas niveau

Au sein d'un composant interne *de bas niveau*, on pourra utiliser des *vérifications faibles* qui visent à *éliminer les erreurs grossières* lors de la réalisation

[IMPORTANT]
====
Il faut *positionner des assertions* vérifiant les *valeurs* de *chaque paramètre*
====

[IMPORTANT]
====
Il faut *activer les assertions sur l'ensemble des environnements* (dev, recette, pre-prod) pour détecter le plus grand nombre de problèmes, *à l'exception de la production* pour des raisons de performances
====

==== Niveaux intermédiaires

Entre les composants internes, il faut *vérifier la cohérence de l'ensemble* et *informer les appelants* en cas de situation anormale.

L'outil de choix pour ces vérifications sont les *exceptions*.

[IMPORTANT]
====
Il faut *lever une exception* pour chaque *situation non gérée* ou *donnée incorrecte*
====

[IMPORTANT]
====
Il faut *varier les types* d'exception pour *permettre un traitement particulier* éventuel

Il faut *regrouper hiérarchiquement* les exceptions pour *segmenter les couches* de middleware
====

[IMPORTANT]
====
Une couche *supérieure* doit *attraper toutes les exceptions* des couches *inférieures*

Une couche ne doit remonter *que* des exceptions *de son propre type*
====

Exemple d'un générateur de site web :

* Consitution
** Le _module principal_ utilise un _module de parsing_, un _module de transformation_, et un _module de sortie_
** Les _modules de parsing_ et le _module de sortie_ utilisent un _module de gestion de fichiers_.
* Exceptions
** le module de gestion de fichier lève des sous classes de `FileExceptions`
** le module de parsing lève des sous classes de `ParsingException`
** le module de transformation lève des sous classes de `TransformException`
** le module de sortie lève des sous classes de `OutputException`
** le module principal lève des `GeneralException`
* Application des consignes
** le _module de parsing_ et le _module de sortie_ *doivent* attraper *toutes* les `FileExceptions`
** le _modules général_ *doit* attraper *toutes* les `ParsingException`, `TransformException` et `OutputException`
** chaque module *ne doit* remonter *que* ses *propres exceptions*
** aucun module de niveau `N+2` *ne doit jamais* voir passer des exceptions d'un niveau `N`

=== Rejet externes

[quote]
Be expressive about your failures

On appellera *composant ouvert à l'extérieur* tout composant dont l'appel *nécessite une transition technique depuis l'appelant*. Par exemple : une requête web mappée sur une classe php, un script qui mappe sur une classe...

[IMPORTANT]
====
Il faut *systématiquement* remonter une information technique *condensée* pouvant *informer les machines* qu'une erreur *a eu lieu*
====

Dans le cas d'un programme ou d'un script on définira *systématiquement* et *explicitement* un *code de retour*, respectant les principes UNIX (retourner zéro en cas de succès, non-zéro en cas d'erreur, et tant que faire se peut, on distinguera chaque cas d'erreur par un code de sortie différnt)

Dans le cas d'une IHM, on affichera le code de retour dans la fenêtre d'erreur

Dans le cas d'une API ou d'un webservice, on retournera le code d'erreur à l'appelant en tant que données de la réponse, ou dans l'enveloppe de la réponse (selon le protocole utilisé)

Dans tous les cas, on prendra soin de logguer aussi ce code de retour dans le cas où une fonctionnalité de log est disponible

[IMPORTANT]
====
Il faut pouvoir remonter une *information textuelle détaillée* pouvant *informer les éventuel humain* du *détail de l'erreur* qui a eu lieu
====

Dans le cas d'un *programme*, d'un *script*, ou d'une *IHM*, on *affichera* systématiquement le message d'erreur signalé

Dans le cas d'une *API* le message d'erreur _n'est pas obligatoire_ (car il ne sert normalement qu'au développeur) : s'il est disponible, on le *retransmettra à l'appelant* en tant que *données de la réponse*, ou dans l'enveloppe de la réponse (selon le protocole utilisé)

Dans tous les cas, on prendra soin de logguer aussi ce message retour dans le cas où une fonctionnalité de log est disponible

=== Comportement attendu

[quote]
Donner le résultat attendu, ou bien remonter le problème

[IMPORTANT]
====
Il faut arrêter tout traitement en cours, et rendre la main, lorsqu'une erreur survient
====

Le seul et unique cas où on doit fournir un résultat, est le cas où tout s'est passé correctement
