= Introduction

== Croissance du savoir

Le savoir humain s'est construit de génération en génération : on apprend un certain nombre de choses, on en découvre éventuellement de nouvelles,  et on transmet éventuellement ce savoir, afin d'alimenter les générations suivantes. Ceci est bien sûr valable quel que soit le domaine, y compris (et surtout !) l'informatique.

Il y a deux facteurs limitants à cette dynamique de croissance du savoir :

* la quantité de choses apprise : moins on apprend, plus on est voués à re-découvrir les choses déjà découvertes par d'autres, ce qui entraîne une perte de temps et d'énergie
* la quantité de choses transmises : moins on transmet, plus le temps et l'énergie dévouée à ces découvertes est perdue pour la communauté, ce qui entraîne une perte de temps et d'énergie

== Pourquoi ce document ?

Au regard de la section ci-dessus, le présent document vise donc (dans la limite de ses moyens) à faciliter à la fois l'apprentissage et la transmission du savoir.

Nous rédigeons ce document en partant des principes suivants :

* un ensemble de connaissances existent déjà et peuvent être transmises
* une majorité de problèmes ont déjà découvert, étudiés et résolus
* une mise en forme synthétique, brève et claire permet une transmission et une acquisition facilitée

== Présentation du contenu

Ce guide vise donc à présenter de manière organisée et synthétique, l'ensemble des problématiques à connaître, et à appliquer lors de la conception ou la réalisation d'un élément.

Bien sûr, ces principes sont applicables indépendamment de l'ampleur, de la criticité, ou de la longévité de l'élement concerné.

Ce document est organisés par thèmes, où l'on présente des *classes de problèmes*. Pour chacun, on présentera les points d'attention afférents, les solutions typiques permettant de les traiter de la *meilleure manière connue*, et les déclinaisons directes pour le projet en cours.

Le document restera cependant général : chaque point abordé sera expliqué, un exemple sera éventuellement donné, et des préceptes de mise en oeuvre de solution seront fournis. On pourra donc le comparer à une encyclopédie sur la cuisine, plutôt qu'un livre de recette.

Chaque partie abordera un ensemble de problèmes, avec des sections dédiées à chaque point thématique relevant de cette classe de problèmes.

== Évolution

Bien sûr, ce document a vocation à évoluer, pour aborder de nouvelles thématiques, ou améliorer les solutions proposées, en fonction de nos expériences, et des suggestions qui seront faites.
