== Scripts shell

[quote]
Un "script en une ligne" n'est pas un script de production (à de rares exceptions)

=== Script, programme, application ?

[quote]
Un "script de 100+ lignes" n'est pas un script : c'est un programme
Un "script de 1000+ lignes" n'est pas un script : c'est une application

[IMPORTANT]
====
Il faut reduire l'utilisation des scripts shell aux cas les plus simples, et privilégier à la place un programme basé sur un language riche dans les autres cas
====

Il manque aux scripts shell la clarté et surtout la robustesse nécessaire pour faire "plus".

Un script shell est très adapté pour créer des "lanceurs de commande", par exemple : définir quelques variables d'environnement, passer un lot de paramètres pré-définis, alimenter les entrées et rediriger ou dupliquer les sorties

En effet, il manque aux scripts le contrôle simple du flux d'exécution (la pile d'appel + le confort des exceptions), la détection d'erreurs habituelles (utilisation d'une variable non définie), les structures de données "au delà de la clé-valeur" sont fastidieuses

Il est estimé qu'à _robustesse et contrôles égaux_, un script shell est environ 50% plus volumineux qu'un programme utilisant une technologie plus robuste, ce qui augmente la complexité de la maintenance, et de la lecture

L'avantage des shell, c'est que toute machine POSIX en dispose d'au moins un, ainsi que de PERL. Sous Linux il y quasiment toujours PYTHON, et il est toujours possible d'installer PHP, Java ... Il faut choisir les outils les plus adaptés à la tâche en cours

[IMPORTANT]
====
S'il existe une contrainte technologique (obligation) ou pragmatique (maintenance de l'existant) pour continuer à utiliser un script shell, se référer aux sections suivante
====

=== Quel interprêteur ?

Sachant :

* qu'un script shell peut utiliser l'une ou l'autre syntaxe de shell (`bash`, `dash`, `ksh`, `csh`... ou bien pur POSIX)
* qu'une distribution pourra choisir d'utiliser l'un ou l'autre comme son interprêteur par défaut (`sh`)

[IMPORTANT]
====
Il faut savoir *identifier quel syntaxe* est utilisée par le script

Il faut *expliciter l'interprêteur utilisé*, afin d'assurer la portabilité et pour indiquer à l'utilisateur quelle syntaxe utiliser pour les corrections et ajouts éventuels

Il *ne faut spécifier `sh`* que si on *garanti* le fait que l'ensemble de la syntaxe est *compatible POSIX*
====

=== Séparation des commandes

[IMPORTANT]
====
Il faut *séparer chaque commande* pour pouvoir *détecter chaque erreur*
====

Ce précepte est issu des constats suivant :

* en cas d'erreur, pour savoir quoi faire, un script ne dispose que :
** du code de retour
** de la sortie standard éventuellement capturée
** de la sortie d'erreur éventuellement capturée
* et lorsqu'une chaine de commande est exécutée :
** les I/O standards ne sont pas capturables
** les codes de retour sont gérés par la chaîne de commande

Exemple pour la commande "simple" suivante :

[source,bash]
----
find ${CHEMIN} | grep -f filter.txt | sed -e 'script' | xargs rm
----

Les cas d'erreur possible (non exaustifs !) :

* si `find` échoue car un des répertoire constituant ${CHEMIN} n'est pas explorable (ie n'existe pas, ou bien pas de `x` dans les permissions), alors find échouera avec une erreur non zéro, et la chaine de commande s'arrêtera là

* si `grep` échoue
** soit car le fichier de filtre n'existe pas ou n'est pas lisible des répertoire constituant ${CHEMIN} n'est pas explorable (ie n'existe pas, ou bien pas de `x` dans les permissions), alors find échouera avec une erreur non zéro, et la chaine de commande s'arrêtera là
** soit il renvoie aussi non-zéro car rien n'a matché

* si `sed` échoue parce qu'il y a une erreur dans l'exécution du script

* si l'une ou l'autre partie du rm sur les fichiers échoue, rm renverra non-zéro

Du coup, *une fois la chaine exécutée*, il est *impossible de déterminer* au sein du script *quelle partie* de la commande a *causé l'echec*

En conséquence, une autre formulation de cette commande serait à privilégier :

[source,bash]
----
FILES=$(find ${CHEMIN})
[[ ${?} -eq 0 ]] || { echo "ERREUR: Problème lors de la recherche de fichiers"; return 1; }

[[ -n "${FILES}" ]] || { echo "DEBUG: pas de fichiers trouvés"; return 0; }

MATCHES=$(grep -f filter.txt ${FILES})
case ${?} in
    0) ;;
    1) echo "DEBUG: Pas de match trouvés"; return 0 ;;
    *) echo "ERREUR: Problème lors de la recherche de motifs"; return 1 ;;
esac

FILES=$(echo "${MATCHES}" | sed -e 'script')
[[ ${?} -eq 0 ]] || { echo "ERREUR: Problème lors de la transformation"; return 1; }

[[ -n "${FILES}" ]] || { echo "DEBUG: Aucun fichier à supprimer"; return 0; }

\rm ${FILES}
[[ ${?} -eq 0 ]] || { echo "ERREUR: Problème lors de la suppression de fichiers"; return 1; }
----

Cette version est certes plus verbeuse, et elle a pris un peu plus de temps à réaliser, mais elle surtout bien *plus robuste et exploitable*.

Par exemple, le jour où "ça ne marche plus" parce qu'un `chmod -X` a été mal fait, ou parce qu'on ajouté un motif qui ne compile pas à la list blanche, _l'utilisateur_ saura exactement _quelle opération a planté_ : il pourra plus facilement comprendre et résoudre le problème par lui même,  sans besoin de remonter aux référents.

Encore une fois, *on facilite la vie de l'utilisateur* et on *gagne en précision et en rapidité* lors des diagnostics de problèmes, ce qui entraîne un gain de temps et une hausse de la confiance envers le produit.

=== Vérification systématique

[IMPORTANT]
====
Il faut *vérifier les code de sortie* spécifiques à chaque commande
====

La norme POSIX indique qu'un code de sortie `0` signifie "pas d'erreur", et qu'une erreur a eu lieu s'il n'y a pas eu d'erreur.

Se créer une fonction `expect_exit VALEUR` qui teste que `${?}` vaut bien VALEUR, permet de vérifier chaque étape.

Attention aux programmes particuliers (GNU find par exemple) qui renvoie `0` si quelque chose a été trouvé, `1` si rien n'a été trouvé, et `2` si une erreur a été rencontrée

D'autres programmes mal conçus ne renvoient pas de code d'erreur en cas de problème, il faut alors trouver une autre manière de détecter les erreurs, et factoriser la solution dans une fonction

=== Factorisation et réutilisation

Il est extrêmement facile de transposer chaque opération (cf l'exemple de la section <<Séparation des commandes>>) en une fonction paramétrable, qui vérifie les paramètres, exécute la commande, log et vérifie les erreurs après exécution.

[IMPORTANT]
====
Il faut *factoriser le code de gestion d'erreur* et de logging pour permettre une réutilisation simple
====

Par exemple pour l'opération "find" :

[source,bash]
----
function _find {
    local __CHEMIN __RESULT

    __CHEMIN=${1}
    [[ -n "${__CHEMIN}" ]] || _show_log_err "Le chemin est nécessaire"; return 1; }

    shift

    __RESULT=$(find ${__CHEMIN} "${@}")
    [[ ${?} -eq 0 ]] || { _show_log_err "Problème lors de la recherche"; return 1; }

    echo "${__RESULT}"
    return 0
}
----

Qu'on pourra utiliser aussi simplement que qu'habituellement :

[source,bash]
----
_find /tmp -type f | grep toto
----

L'avantage de cette démarche, est qu'on a une *gestion automatique et transparente* de *tous* les *cas d'erreur* pouvant survenir quand on utilise cette commande standard.

On peut alors *constituer une librairie de fonction* qu'on pourra *ré-utiliser* dans n'importe quel script, avec une *gestion homogène* des erreurs.

=== Invoquer les commandes de manière stable

[quote]
Les commandes qu'on "tape" ne sont pas des commandes adéquates pour les scripts

[IMPORTANT]
====
Il faut *choisir les commandes* ayant les interfaces *les plus stables*, et les invoquer de manière à *réduire les adaptations* dans le temps

* Préférer les informations issues de `/proc` et `/sys` plutôt que des commandes qui ne font que récupérer ces informations et les reformater "pour les humains"

* Préférer les commandes ayant un formattage fixe ou absolument paramétrable (tel que `find -printf`, `stat`) aux commandes habituelle (`ls` et toutes ses options) et pareil pour `find -delete` en remplacement de `rm`
====

Un script shell invoque un grand nombre de commandes, et il est habituel d'utiliser _dans un script_ les mêmes commandes que celles qu'un être humain passerait interactivement, ce qui se révèle être une source de problèmes, alors qu'il y a toujours plusieurs manières de faire la même chose

La majorité des programmes POSIX sont compatibles avec les librairies multi-lingues, et leurs sorties sont adaptées à la configuration du terminal (local ou distant) de l'utilisateur invoquant la commande (ou du script qui l'invoque)

Ils tiennent compte de la *locale* et de l'*encodage*, et/ou du fait que le terminal soit interactif (`tty` ou non)

Par exemple ils peuvent modifier le format de date. Et cerise sur le gâteau, ces programmes évoluent, ce qui fait que leur format d'entrées et sorties évoluent et que les scripts les utilisant doivent s'adapter

=== Les `alias`

[quote]
Tenir compte de la personnalisation de l'environnement

[IMPORTANT]
====
Il faut invoquer chaque commandes "habituelles" avec un _backslash_ en tête, afin de court-circuiter les éventuels alias utilisateur qui modifieraient le comportement
====

Le shell `bash` (entre autres) permet de définir des alias, qui modifient la commande passée, en remplaçant. Par exemple, CentOS positionne un alias `rm='rm -i'` pour le compte root, ce qui fait que tout script utilisant `rm` serait obligé de passer l'option `-f` pour éviter le prompt

Sauf que `-f` rend aussi silencieux et aucune erreur ne sera affichée, et force le code de sortie à zéro, ce qui fait qu'aucune erreur ne peut être détecte

Une première solution est d'invoquer `\rm`, ce qui ignore les éventuels alias

Une autre solution est d'utiliser `\find ... -delete` permet aussi une suppression beaucoup plus contrôlée

=== Variables locales et globales

[IMPORTANT]
====
Il faut réduire le scope des variables et rendre leur noms intelligibles
====

En l'absence de précision, toute variable shell est globale, ce qui n'est pas une bonne pratique. Utiliser le mot-clé `local` dans les `function`s BASH pour définir une variable locale, ou le mot clé `typeset` en KSH

Spécialiser leur nom en le préfixant d'un double _underscore_ pour faciliter la différenciation entre variables locales et globales.

Récupérer les arguments passés (au script et aux fonctions) dans des variables aux noms maîtriséspour une meilleure intelligibilité

.TEXT est global, __CHEMIN et __RESULT sont locales
----
TEXT="toto"
function suffix_toto {
    local __CHEMIN="${1}" __RESULT
    __RESULT="${__CHEMIN}_${TEXT}"
    return "${__RESULT}"
----

=== Valeur de retour vs code retour

function
print
return
exit

=== Pièges

utiliser ${AZE} plutôt que $AZE à cause de ce qui suit

=== Personalisation

variables par défaut en début de script
surcharge des variables par défaut
getopts ou source



aucun élément ne doit être hard-codé

ssh batch mode pour interdire le prompt qui hang la connexion
ssh pre-test connexion avant commande pour retour erreur
ssh multi commande => 1 série de cmd plutôt qu'une série de ssh, préférer invoc un script distant copié à l'avance quand la logique devient complexe

===
scope des variables
surcharge éventuelle pour les éléments non paramétrables pour éviter les modification
vérification des code de retour
segmentation en commandes unitaires plutôt qu'en chaine
factoriser le code en fonction
factoriser le code en librairies
